name: Update Deployed Shiny App

on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'

jobs:
  Update-Deployed-App:
    name: Update the deployed Shiny App to include up to date shots
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3  

    - uses: r-lib/actions/setup-r@v2
      with: 
        use-public-rspm: true
        r-version: 'release'
    - name: Install libcurl and libssl on Linux
      run: sudo apt-get -y install libcurl4-openssl-dev
      shell: bash
      
    - name: Cache CRAN packages
      uses: actions/cache@v3 
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}

    - name: Install required packages from CRAN
      uses: r-lib/actions/setup-r-dependencies@v2
      with: 
        packages: rsconnect
        
    - name: Run R update script
      run: Rscript deployment.R
      shell: bash
